# ----------------------------
# Makefile Options
# ----------------------------

NAME = SNAKE
COMPRESSED = YES

CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
