# ----------------------------
# Makefile Options
# ----------------------------

NAME = MINESWPR
ICON = icon.png
DESCRIPTION = "Mine Sweeper game"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
